function itksnap2cartool( FilePath )
%itksnap2cartool: flips ITK-SNAP segmentation results image such that the
% image used to create the image and generated by Cartool, is aligned
%
% Renaud Marquis @ FBM lab, March 2018

V = spm_vol(FilePath);
D = spm_read_vols(V);
Vnew = V;
Vnew.fname = spm_file(Vnew.fname,'prefix','r');
Dnew = nan(size(D));
for s = 1:size(D,3)
    Dnew(:,:,s) = rot90(D(:,:,s),2);
end
spm_write_vol(Vnew,Dnew);

end