function EEGclean = my_ICA_backtransform( ICA_results, IC2remove)
% my_ICA_backtransform: reconstruct EEG without specified ICA components
%
% my_ICA_backtransform( ICA_results, IC2remove)
%
%  Inputs
% --------
% ICA_results: string, path to .mat file as generated by my_ICA.m
% IC2remove: indices of independent components to remove
%
%  Outputs
% --------
% EEGclean: reconstructed EEG
%
%-------------------------------------------------------------------------
% Author:  Frédéric Grouiller, FBMLab, Geneva (frederic.grouiller@unige.ch)
%--------------------------------------------------------------------------
% refacto for saving as .sef file, Renaud Marquis @ FBMlab, September 2018,
% updated May 2019
%--------------------------------------------------------------------------

load(ICA_results)

% back-transform
EEGclean = Winv(:,setdiff(1:size(Winv,2),IC2remove))*Activations(setdiff(1:size(Winv,2),IC2remove),:); %#ok<NODEF>

end
