function [NumClusters,NumFiles,Clust,Maps,GEV,Gamma,Silhouettes,DaviesBould,PtBiserial,DunnR,KL,MeanCrit,MetaCrit] = read_errordata_Cartool(openfilename)
% read_errordata_Cartool: opens a Cartool segmentation goodness-of-fit file (.error.data)
%
% [NumClusters,NumFiles,Clust,Maps,GEV,Gamma,Silhouettes,DaviesBould,PtBiserial,DunnR,KL,MeanCrit,MetaCrit] = read_errordata_Cartool(openfilename)
%
%  Inputs
% --------
% openfilename: string, path to .error.data file
%
%  Outputs
% ---------
% NumClusters : 
% NumFiles    :
% Clust       :
% Maps        :
% GEV         :
% Gamma       :
% Silhouettes : 
% DaviesBould : 
% PtBiserial  : 
% DunnR       : 
% KL          :
% MeanCrit    : 
% MetaCrit    : 
%
%-------------------------------------------------------------------------
% Cartool: https://sites.google.com/site/cartoolcommunity
%-------------------------------------------------------------------------
% Renaud Marquis @ FBMlab, May 2019
%-------------------------------------------------------------------------

% open filename for reading in text mode
fid=fopen(openfilename,'r');

% for .eph files
if strcmp(openfilename(end-10:end),'.error.data')==1
    
    % read header
    eph=textscan(fid,'%s','delimiter','/n');
    eph=eph{1};
    
    NumClusters=sscanf(eph{1},'%*f %f',1);
    H2 = regexp(eph{2},'\s','split');
    NumFiles = str2double(H2{1});
    
    [Clust,Maps,GEV,Gamma,Silhouettes,DaviesBould,PtBiserial,DunnR,KL,MeanCrit,MetaCrit] = ...
        import_errordata_data(openfilename);

else
    error('incorrect file type');
end

% close file
fclose(fid);

end

function [Clust,Maps,GEV,Gamma,Silhouettes,DaviesBould,PtBiserial,DunnR,KL,MeanCrit,MetaCrit] = import_errordata_data(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [CLUST,MAPS,GEV,GAMMA,SILHOUETTES,DAVIESBOULD,PTBISERIAL,DUNNR,KL,MEANCRIT,METACRIT]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [CLUST,MAPS,GEV,GAMMA,SILHOUETTES,DAVIESBOULD,PTBISERIAL,DUNNR,KL,MEANCRIT,METACRIT]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Clust,Maps,GEV,Gamma,Silhouettes,DaviesBould,PtBiserial,DunnR,KL,MeanCrit,MetaCrit] = importfile('GC_AG78_pos.error.data',3, 17);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/05/30 10:08:05

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

FID = fopen(filename,'r');

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%*s%[^\n\r]';

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(FID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(FID);
    dataArrayBlock = textscan(FID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

fclose(FID);

%% Allocate imported array to column variable names
Clust = dataArray{:, 1};
Maps = dataArray{:, 2};
GEV = dataArray{:, 3};
Gamma = dataArray{:, 4};
Silhouettes = dataArray{:, 5};
DaviesBould = dataArray{:, 6};
PtBiserial = dataArray{:, 7};
DunnR = dataArray{:, 8};
KL = dataArray{:, 9};
MeanCrit = dataArray{:, 10};
MetaCrit = dataArray{:, 11};

end